# Generated by Django 4.2.3 on 2023-09-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.TextField()),
                ("definition", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Bottle",
        ),
    ]
