# Generated by Django 4.2.3 on 2023-09-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_webscraper_definition_webscraper_word_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebScraper",
        ),
        migrations.AlterField(
            model_name="word",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
