# Generated by Django 4.2.4 on 2023-10-05 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_word_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="user",
        ),
    ]
